export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_ALREADY_SOLD: 'ITEM_ALREADY_SOLD',
  ITEM_CHANGED: 'ITEM_CHANGED',

  BUYER_NOT_FOUND: 'BUYER_NOT_FOUND',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  SELF_PURCHASE_NOT_ALLOWED: 'SELF_PURCHASE_NOT_ALLOWED',

  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  PURCHASE_BUSY: 'PURCHASE_BUSY',
};

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
